-- MySQL Script generated by MySQL Workbench
-- 11/18/16 17:41:57
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema horarios
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `horarios` ;

-- -----------------------------------------------------
-- Schema horarios
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `horarios` DEFAULT CHARACTER SET utf8 ;
USE `horarios` ;

-- -----------------------------------------------------
-- Table `horarios`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`usuario` ;

CREATE TABLE IF NOT EXISTS `horarios`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apepaterno` VARCHAR(45) NOT NULL,
  `apematerno` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`aula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`aula` ;

CREATE TABLE IF NOT EXISTS `horarios`.`aula` (
  `idaula` INT NOT NULL AUTO_INCREMENT,
  `nroaula` VARCHAR(45) NOT NULL,
  `aforomax` VARCHAR(45) NOT NULL,
  `pizarra` VARCHAR(45) NOT NULL,
  `proyector` VARCHAR(45) NOT NULL,
  `audio` VARCHAR(45) NOT NULL,
  `ecram` VARCHAR(45) NOT NULL,
  `equipopc` VARCHAR(45) NOT NULL,
  `nivel` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idaula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`docente` ;

CREATE TABLE IF NOT EXISTS `horarios`.`docente` (
  `iddocente` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `limfisica` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddocente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`disponibilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`disponibilidad` ;

CREATE TABLE IF NOT EXISTS `horarios`.`disponibilidad` (
  `iddisponibilidad` INT NOT NULL AUTO_INCREMENT,
  `iddocente` INT NOT NULL,
  `horainicio` VARCHAR(45) NOT NULL,
  `horafinal` VARCHAR(45) NOT NULL,
  `dia` VARCHAR(45) NOT NULL,
  `ciclo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iddisponibilidad`),
  INDEX `fk_iddocente_idx` (`iddocente` ASC),
  CONSTRAINT `fk_iddocente`
    FOREIGN KEY (`iddocente`)
    REFERENCES `horarios`.`docente` (`iddocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`asignatura` ;

CREATE TABLE IF NOT EXISTS `horarios`.`asignatura` (
  `idasignatura` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `horas` TINYINT(1) NOT NULL,
  `ciclo` VARCHAR(45) NOT NULL,
  `plan` VARCHAR(45) NOT NULL,
  `creditos` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `horaspractica` TINYINT(1) NOT NULL,
  `horasteoria` TINYINT(1) NOT NULL,
  `horaslaboratorio` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idasignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`curso` ;

CREATE TABLE IF NOT EXISTS `horarios`.`curso` (
  `idcurso` INT NOT NULL AUTO_INCREMENT,
  `iddocente` INT NOT NULL,
  `idasignatura` INT NOT NULL,
  `idaula` INT NOT NULL,
  `horainicio` VARCHAR(45) NOT NULL,
  `horafinal` VARCHAR(45) NOT NULL,
  `seccion` VARCHAR(45) NOT NULL,
  
  PRIMARY KEY (`idcurso`),
  INDEX `fk_curso_idx` (`iddocente` ASC),
  INDEX `fk_idasinatura_idx` (`idasignatura` ASC),
  INDEX `fk_idaula_idx` (`idaula` ASC),
  CONSTRAINT `fk_curso`
    FOREIGN KEY (`iddocente`)
    REFERENCES `horarios`.`docente` (`iddocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idasinatura`
    FOREIGN KEY (`idasignatura`)
    REFERENCES `horarios`.`asignatura` (`idasignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idaula`
    FOREIGN KEY (`idaula`)
    REFERENCES `horarios`.`aula` (`idaula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horarios`.`dictado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `horarios`.`dictado` ;

CREATE TABLE IF NOT EXISTS `horarios`.`dictado` (
  `iddictado` INT NOT NULL AUTO_INCREMENT,
  `iddocente` INT NOT NULL,
  `idasignatura` INT NOT NULL,
  PRIMARY KEY (`iddictado`),
  INDEX `fk_iddocente_idx` (`iddocente` ASC),
  INDEX `fk_idasinatura_idx` (`idasignatura` ASC),
  CONSTRAINT `fk_iddocente2`
    FOREIGN KEY (`iddocente`)
    REFERENCES `horarios`.`docente` (`iddocente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idasinatura2`
    FOREIGN KEY (`idasignatura`)
    REFERENCES `horarios`.`asignatura` (`idasignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
